build: false

environment:
  matrix:
    - PYTHON_VERSION: 3.6
      MINICONDA: C:/Miniconda36-x64
init:
  - ECHO %PYTHON_VERSION% %MINICONDA%
  - ECHO conda --version

install:
  - set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=%PYTHON_VERSION% numpy scipy scikit-learn pandas pytest
  - activate test-environment
  - pip install dlib
  - pip install imageio
  - pip install scikit-image

test_script:
  - set PYTHONPATH=%PYTHONPATH%;%CD%
  - pytest -sv --ignore=mlxtend/plotting

notifications:

  # Email
  - provider: Email
    to:
      - mail@sebastianraschka.com
    subject: 'Build {{status}}'
    message: "{{message}}, {{commitId}}, ..."
    on_build_status_changed: true