name: mlxtend
channels:
  - conda-forge
dependencies:
  - flake8>=4.0.1
  - numpy>=1.21.4
  - pandas>=1.3.5
  - pip>=21.3.1
  - pytest>=6.2.5
  - scikit-learn>=1.0.2
  - scipy>=1.7.3
  - setuptools>=59.4.0
  - pip:
    - markdown>=3.3.6
