name: mlxtend
channels:
  - conda-forge
dependencies:
  - flake8>=4.0.1
  - numpy>=1.21.0,<2.4.0
  - pandas>=2.3.3
  - scipy>=1.16.3
  - scikit-learn>=1.8.0
  - matplotlib>=3.10.8
  - joblib>=1.5.2
  - pip>=21.3.1
  - pytest>=6.2.5
  - setuptools>=59.4.0
  - pip:
      - markdown>=3.3.6
