name: Lint using black and isort

on: [pull_request]

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install isort and black
        run: |
          python -m pip install --upgrade pip
          pip install isort black
      - name: Run isort and black
        run: |
          isort -p --check --diff --line-length 88 --multi-line 3 --py 39 --profile black mlxtend/*
          black --check --diff mlxtend/*