
name: PEP8
on: [pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Python 3.7
      uses: actions/setup-python@master
      with:
        version: 3.7
    - name: flake8
      run: |
        pip install flake8
        flake8 .  --show-source --statistics
