name: Unit tests (conda)

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    env:
      GITHUB_ACTIONS_CI: true
    steps:
      - uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.11
          channels: conda-forge
          activate-environment: mlxtend
          environment-file: environment.yml
          create-env-file: true

      - name: Install test dependencies (conda)
        shell: bash -l {0}
        run: |
          conda install -y pytest coverage

      - name: Install package and run tests
        shell: bash -l {0}
        run: |
          python -m pip install -e .
          python -c "import numpy; print('NumPy:', numpy.__version__)"
          python -c "import scipy; print('SciPy:', scipy.__version__)"
          python -c "import sklearn; print('Scikit-learn:', sklearn.__version__)"
          python -c "import pandas; print('Pandas:', pandas.__version__)"
          coverage run --source=mlxtend --branch -m pytest mlxtend
          coverage xml

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v4
